### ISSUE TITLE
Mac環境でのデバッグ実行

### ISSUE THREAD

**Issue by twilio-master** [yu36/public-oauth-jwt-blog#1]
こんにちは。このプログラムとブログの記事が大変参考になりました。
一点だけご提案です。
Mac環境でデバッグ実行をすると、プログラムのパスがうまく反映されずにエラーになってしまうようです。
そこで、`.vscode/launch.json`内で、`${pathSeparator}`を使ってみるのはどうでしょう。
こちらの環境ではこれでうまく実行できました。

```
{
	// IntelliSense を使用して利用可能な属性を学べます。
	// 既存の属性の説明をホバーして表示します。
	// 詳細情報は次を確認してください: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "プログラムの起動",
			"skipFiles": [
				"<node_internals>/**"
			],
			"program": "${workspaceFolder}${pathSeparator}src${pathSeparator}index.js"
		}
	]
}
```

**Comment by yu36** [comment]
@twilio-master さん
ご連絡ありがとうございます。 🙇 
こちらWindows環境で確認しており、Mac環境の考慮が出来ていませんでした。
頂いたデバッグ設定のようなパス区切りの設定とすると、こちらのWindows環境でも問題なく動作することを確認できました。修正して取り込みます。

**Comment by yu36** [comment]
close
